AllCops:
  TargetRubyVersion: 2.6.5

Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false