default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASS") %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: marshmallows_auth_development

test:
  <<: *default
  database: marshmallows_auth_test

production:
  <<: *default
  database: marshmallows_auth_production
