default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASS") %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: marshmallows_auth_development

test:
  <<: *default
  database: marshmallows_auth_test

production:
  <<: *default
  database: marshmallows_auth_production
