apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: marsmallows-auth
spec:
  type: LoadBalancer
  selector:
    app: marsmallows-auth
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql