apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsmallows-auth-deployment
  labels:
    app: marsmallows-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marsmallows-auth
  template:
    metadata:
      labels:
        app: marsmallows-auth
    spec:
      containers:
      - name: marsmallows-auth
        image: mm_auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        command: ["bundle", "exec", "rails", "server"]
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: MYSQL_HOST 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: MYSQL_USER
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: auth-env
              key: MYSQL_PASS
