apiVersion: v1
kind: Service
metadata:
  name: marsmallows-auth-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: marsmallows-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http