apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsmallows-auth-mysql
  labels:
    app: marsmallows-auth
spec:
  selector:
    matchLabels:
      app: marsmallows-auth
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: marsmallows-auth
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
