// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/requests.proto

package requests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb5615461bff173, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

const Default_Request_Id int32 = 0

func (m *Request) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return Default_Request_Id
}

type Auth struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id,def=1" json:"id,omitempty"`
	Sid                  *int32   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	PublicKey            *string  `protobuf:"bytes,3,req,name=publicKey" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb5615461bff173, []int{1}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

const Default_Auth_Id int32 = 1

func (m *Auth) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return Default_Auth_Id
}

func (m *Auth) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *Auth) GetPublicKey() string {
	if m != nil && m.PublicKey != nil {
		return *m.PublicKey
	}
	return ""
}

type AuthAck struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id,def=2" json:"id,omitempty"`
	Sid                  *int32   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	PublicKey            *string  `protobuf:"bytes,3,req,name=publicKey" json:"publicKey,omitempty"`
	Address              *string  `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Port                 *int32   `protobuf:"varint,5,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthAck) Reset()         { *m = AuthAck{} }
func (m *AuthAck) String() string { return proto.CompactTextString(m) }
func (*AuthAck) ProtoMessage()    {}
func (*AuthAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb5615461bff173, []int{2}
}

func (m *AuthAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthAck.Unmarshal(m, b)
}
func (m *AuthAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthAck.Marshal(b, m, deterministic)
}
func (m *AuthAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthAck.Merge(m, src)
}
func (m *AuthAck) XXX_Size() int {
	return xxx_messageInfo_AuthAck.Size(m)
}
func (m *AuthAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthAck.DiscardUnknown(m)
}

var xxx_messageInfo_AuthAck proto.InternalMessageInfo

const Default_AuthAck_Id int32 = 2

func (m *AuthAck) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return Default_AuthAck_Id
}

func (m *AuthAck) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *AuthAck) GetPublicKey() string {
	if m != nil && m.PublicKey != nil {
		return *m.PublicKey
	}
	return ""
}

func (m *AuthAck) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *AuthAck) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type Hearbeat struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id,def=3" json:"id,omitempty"`
	Token                *string  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	Timestamp            *int64   `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hearbeat) Reset()         { *m = Hearbeat{} }
func (m *Hearbeat) String() string { return proto.CompactTextString(m) }
func (*Hearbeat) ProtoMessage()    {}
func (*Hearbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb5615461bff173, []int{3}
}

func (m *Hearbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hearbeat.Unmarshal(m, b)
}
func (m *Hearbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hearbeat.Marshal(b, m, deterministic)
}
func (m *Hearbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hearbeat.Merge(m, src)
}
func (m *Hearbeat) XXX_Size() int {
	return xxx_messageInfo_Hearbeat.Size(m)
}
func (m *Hearbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hearbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Hearbeat proto.InternalMessageInfo

const Default_Hearbeat_Id int32 = 3

func (m *Hearbeat) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return Default_Hearbeat_Id
}

func (m *Hearbeat) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Hearbeat) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "requests.Request")
	proto.RegisterType((*Auth)(nil), "requests.Auth")
	proto.RegisterType((*AuthAck)(nil), "requests.AuthAck")
	proto.RegisterType((*Hearbeat)(nil), "requests.Hearbeat")
}

func init() { proto.RegisterFile("protocol/requests.proto", fileDescriptor_9eb5615461bff173) }

var fileDescriptor_9eb5615461bff173 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x15, 0x27, 0x51, 0x9a, 0x9b, 0xc0, 0x42, 0xc2, 0x43, 0x07, 0xcb, 0x93, 0x27, 0xfe,
	0x6e, 0x6c, 0xdd, 0x40, 0x4c, 0xdc, 0x37, 0x70, 0xe3, 0x93, 0xb0, 0xda, 0x62, 0x63, 0x3b, 0x03,
	0x7c, 0x7a, 0x64, 0x57, 0x55, 0x15, 0xc6, 0x6e, 0xef, 0xbd, 0x93, 0x7e, 0xef, 0x1d, 0xdc, 0x86,
	0xe8, 0xb3, 0x9f, 0xfc, 0xfe, 0x3e, 0xd2, 0xf7, 0x4c, 0x29, 0xa7, 0xbb, 0x9a, 0xf0, 0xd5, 0xc9,
	0xab, 0x35, 0x0c, 0x78, 0xd4, 0xfc, 0x1a, 0x98, 0xb3, 0xa2, 0x91, 0x8d, 0xee, 0x5f, 0x9a, 0x07,
	0x64, 0xce, 0xaa, 0x37, 0xe8, 0x36, 0x73, 0xfe, 0x5c, 0x9e, 0x1e, 0xcb, 0x89, 0x5f, 0x41, 0x9b,
	0x9c, 0x15, 0x4c, 0x32, 0xdd, 0x63, 0x91, 0x7c, 0x0d, 0x63, 0x98, 0xb7, 0x7b, 0x37, 0xbd, 0xd3,
	0x8f, 0x68, 0x25, 0xd3, 0x23, 0x9e, 0x03, 0xf5, 0x0b, 0x43, 0x41, 0x6d, 0xa6, 0xdd, 0x92, 0xf6,
	0x74, 0x09, 0x8d, 0x0b, 0x18, 0x8c, 0xb5, 0x91, 0x52, 0x12, 0x9d, 0x6c, 0xf4, 0x88, 0x27, 0xcb,
	0x39, 0x74, 0xc1, 0xc7, 0x2c, 0xfa, 0x82, 0xc7, 0xaa, 0xd5, 0x07, 0xac, 0x5e, 0xc9, 0xc4, 0x2d,
	0x99, 0x7f, 0x5f, 0x3e, 0xd7, 0xf2, 0x1b, 0xe8, 0xb3, 0xdf, 0xd1, 0x57, 0xad, 0x1f, 0xf1, 0x68,
	0xca, 0x80, 0xec, 0x0e, 0x94, 0xb2, 0x39, 0x84, 0x3a, 0xa0, 0xc5, 0x73, 0xf0, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x0e, 0xda, 0xb9, 0x3d, 0x5b, 0x01, 0x00, 0x00,
}
